#!/bin/bash
#
# Program: AWS CLI auto install scirpt 
trap 'stop' SIGUSR1 SIGINT SIGHUP SIGQUIT SIGTERM SIGSTOP
PROGRAMNAME=${0##*/}
VERSION=1.0

prefix="/usr/local/aws"
prefix_bin="/usr/local/bin/aws"
awsuri="https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
awscli="awscli-bundle"
tmpdir="/tmp"

stop() {
  exit 0
}

check_env(){
  if [ `which python` ]; then
    py_ver=`python --version 2>&1`
    echo "The AWS CLI will be install in $py_ver"
  else
    echo "**check**: python not install."
    exit 0
  fi

  if [ ! `which wget` ]; then
    sudo apt-get install -y wget
  fi
  
  if [ ! `which unzip` ]; then
    sudo apt-get install -y unzip
  fi
}

get_package() {
  echo -n "Download awscli package ..."
  cd /tmp
  if [ $HTTPS_PROXY ]; then
    curl -x $HTTPS_PROXY -O "$awsuri"
  else
    curl -O "$awsuri"
  fi
}

awscli_install() {
  check_env
  get_package
  echo -n "unzip $awscli.zip ..."
  unzip -q ${tmpdir}/${awscli}.zip -d /tmp
  if [[ 0 -eq $? ]]; then
    echo "OK"
  else
    echo "fail"
    exit 0
  fi

  echo "Install awscli ..."
  sudo ${tmpdir}/${awscli}/install -i "$prefix" -b "$prefix_bin"
  if [ $? -eq 0 ]; then
    rm -rf ${tmpdir}/${awscli}
    echo "clean install package file finish."
  else
    echo "Install awscli failed"
  fi
}

if [ -e config.ini ]; then
  source config.ini
else
  echo "Can not find 'config.ini'"
  exit 1
fi

if which aws; then
  echo "$(which aws) already exist."
  exit 1
else
  awscli_install
fi
